### PR TITLE
Namespace added to GUI and blobulation

### LINKED ISSUE #501: VMD blobulator default buttons needs to be moved

### LINKED ISSUE #508: VMD blobulator needs namespace
Helps protect variables

### PR DESCRIPTION
**Pull request by RL0109**
## Description
Gives both scripts namespaces which allows safe variable calls to functions

## Todos
- [x] Closes #508
- [x] Closes #501 

## Questions
- [x] Does the program function normally?
- [ ] Should the variable names be changed somewhat
- [x] Is the code displaying proper namespace utility? As in does this program correctly utilize namespaces and doesn't needlessly name the variables? 
## Status
- [x] Ready to go

### CODE REVIEW

**Comment by EzryStIago** [comment]
@RL0109 Unexpected behavior (bug?)
Steps to reproduce:
1. Start vmd
2. load structure (8d66 in my case)
3. in the TKconsole: `cd blobulator/VMD_scripts`
4. `source Blob_GUI.tcl`
5. Click default button for L and get this. (so far so good)
image
6. click default button for H and got this error.
image

It looks like the issue was that I hadn't selected a hydropathy scale. Is it possible to initialize the drop-down menu with Kyte-Doolittle?

**Comment by EzryStIago** [comment]
@RL0109 Actual bug:
Given this setup:
image
when I click `Blobulate!` I get this error:
```
Error: invalid command name "blobulate"
invalid command name "blobulate"
invalid command name "blobulate"
    while executing
"blobulate $::blobulator::MolID $::blobulator::Lmin $::blobulator::H $::blobulator::hydropathyScaleDictionaryList"
    (procedure "blobulation" line 10)
    invoked from within
"blobulation "
    invoked from within
".blob.blobulate invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .blob.blobulate"
    (command bound to event)
```

**Review by EzryStIago — APPROVED** [review]
Looks appropriate for the stated scope of the PR.
Regarding variable names, though, could you change w1, w2, and w3 to something more meaningful? I have no idea what they are.

**Review by EzryStIago — CHANGES_REQUESTED** [review]
Can you rename w1, w2, and w3 to something more meaningful?

**Comment by RL0109** [comment]
> Can you rename w1, w2, and w3 to something more meaningful?
These variable names have been changed in its iterative branch

**Review by EzryStIago — APPROVED** [review]

**Review by cpitman-11 — APPROVED** [review]

**Pull request merged**
