### PR TITLE
434 overhaul landing page

### PR DESCRIPTION
**Pull request by cpitman-11**
fixes most items on issue #434 checklist

### CODE REVIEW

**Comment by EzryStIago** [comment]
As noted in blobulator meeting last week, can you change it so the warning message is closer to the top?
image

**Review by EzryStIago — CHANGES_REQUESTED** [review]
Please move the mobile warning to the top of the page.

**Comment by cpitman-11** [comment]
Moved the mobile warning further up the page

**Review by EzryStIago — APPROVED** [review]

**Comment by EzryStIago** [comment]
Works locally

**Pull request merged**
